schema: E4Config
name: e4-all
description: All modes from Empatica E4 sensors
path:
  dir: ${path.openpack.rootdir}/${user.name}/e4/${device}/
  fname: ${sensor}/${session}.csv
  template: ${.dir}/${.fname}
file_format:
  file_type: csv
  columns:
  - name: unixtime
    unit: milli second
  - name: TBA
    unit: null
frame_rate:
  acc: 32Hz
  bvp: 64Hz
  eda: 4Hz
  temp: 4Hz
meta:
  tables: []
nodes:
- e401
- e402
acc: true
