errors:
- note: Overwrite the output path to the data (atr03/04, S0200, S0400) might be a
    possible solution but not applied yet.
  segments:
    boxes: -1
    streams:
    - atr03
    - atr04
    sessions:
    - S0200
    - S0400
  status: PENDING
  title: The position of ATR03 and ATR04 seem to be swapped.
id: 104
meta:
  age_group: 50s
  dominant_hand: Right
  note: ''
  packaging_experience: 1 Month
  scenarios:
    S0100: S1
    S0200: S1
    S0300: S1
    S0400: S1
    S0500: S1
  sex: F
name: U0104
sessions:
  S0100:
    annotated_box: 20
    duration: 50m04s
    end: '2021-11-16T13:07:59+09:00'
    start: '2021-11-16T12:17:55+09:00'
  S0200:
    annotated_box: 20
    duration: 47m03s
    end: '2021-11-16T15:09:10+09:00'
    start: '2021-11-16T14:22:07+09:00'
  S0300:
    annotated_box: 19
    box:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    duration: 37m56s
    end: '2021-11-16T16:08:45+09:00'
    start: '2021-11-16T15:30:49+09:00'
  S0400:
    annotated_box: 10
    box:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    duration: 17m54s
    end: '2021-11-16T16:44:38+09:00'
    start: '2021-11-16T16:26:44+09:00'
