errors:
- note: It seems that the ATR01 is installed in the wrong direction (upside down);
    I corrected this by multiplying the x- and y-axes of the acc data by -1. The gyro
    and quat sequences have not been corrected yet.
  segments:
    boxes: -1
    sessions:
    - S0400
    streams:
    - atr03
  status: partially fixed
  title: ATR01 was attached in the wrong direction.
- status: pending
  title: Video data is missing.
  segments:
    sessions:
    - S0300
    boxes:
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    streams:
    - kinect
  note: Annotation for this segment is pending.
id: 107
meta:
  age_group: 40s
  dominant_hand: Right
  note: ''
  packaging_experience: 3 Years
  scenarios:
    S0100: S1
    S0200: S1
    S0300: S1
    S0400: S1
    S0500: S1
  sex: F
name: U0107
sessions:
  S0100:
    annotated_box: 20
    duration: 37m18s
    end: '2021-12-03T11:47:24+09:00'
    start: '2021-12-03T11:10:06+09:00'
  S0200:
    annotated_box: 20
    duration: 35m26s
    end: '2021-12-03T12:43:16+09:00'
    start: '2021-12-03T12:07:50+09:00'
  S0300:
    annotated_box: 9
    box:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    duration: 14m00s
    end: '2021-12-03T14:06:41+09:00'
    start: '2021-12-03T13:52:41+09:00'
  S0400:
    annotated_box: 20
    duration: 30m17s
    end: '2021-12-03T15:13:26+09:00'
    start: '2021-12-03T14:43:09+09:00'
  S0500:
    annotated_box: 20
    duration: 30m06s
    end: '2021-12-03T16:02:32+09:00'
    start: '2021-12-03T15:32:26+09:00'
