errors:
- note: Kinect data is not available because of some issues in a frame extraction
    program.
  segments:
    boxes:
    - 17
    - 18
    - 19
    - 20
    sessions:
    - S0100
    streams:
    - kinect
    - atr01
    - atr02
    - atr03
    - atr04
  status: PENDING
  title: ATR was not available. Annotation process is suspended.
id: 109
meta:
  age_group: 30s
  dominant_hand: Left
  note: ''
  packaging_experience: 6 Month
  scenarios:
    S0100: S1
    S0200: S1
    S0300: S1
    S0400: S1
    S0500: S1
  sex: M
name: U0109
sessions:
  S0100:
    annotated_box: 16
    box:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    duration: 36m53s
    end: '2021-12-17T13:11:20+09:00'
    start: '2021-12-17T12:34:27+09:00'
  S0200:
    annotated_box: 20
    duration: 45m28s
    end: '2021-12-17T14:29:21+09:00'
    start: '2021-12-17T13:43:53+09:00'
  S0300:
    annotated_box: 20
    duration: 35m26s
    end: '2021-12-17T15:22:51+09:00'
    start: '2021-12-17T14:47:25+09:00'
  S0400:
    annotated_box: 20
    duration: 33m38s
    end: '2021-12-17T16:35:50+09:00'
    start: '2021-12-17T16:02:12+09:00'
  S0500:
    annotated_box: 20
    duration: 33m18s
    end: '2021-12-17T17:31:44+09:00'
    start: '2021-12-17T16:58:26+09:00'
