errors:
- segments:
    boxes: -1
    sessions:
    - S0100
    streams:
    - atr02
  status: NO_FIX_AVAILABLE
  title: ATR02 was attached in the wrong direction.
- segments:
    boxes: -1
    sessions:
    - S0200
    streams:
    - atr03
  status: NO_FIX_AVAILABLE
  title: ATR03 was attached in the wrong direction.
id: 207
meta:
  age_group: 40s
  dominant_hand: Right
  note: ''
  packaging_experience: 20 Month
  scenarios:
    S0100: S2
    S0200: S2
    S0300: S3
    S0400: S3
    S0500: S4
  sex: F
name: U0207
sessions:
  S0100:
    annotated_box: 20
    duration: 29m23s
    end: '2022-03-22T10:49:16+09:00'
    start: '2022-03-22T10:19:53+09:00'
  S0200:
    annotated_box: 20
    duration: 23m06s
    end: '2022-03-22T11:35:44+09:00'
    start: '2022-03-22T11:12:38+09:00'
  S0300:
    annotated_box: 20
    duration: 23m45s
    end: '2022-03-22T12:23:24+09:00'
    start: '2022-03-22T11:59:39+09:00'
  S0400:
    annotated_box: 20
    duration: 23m09s
    end: '2022-03-22T14:03:16+09:00'
    start: '2022-03-22T13:40:07+09:00'
  S0500:
    annotated_box: 20
    duration: 20m41s
    end: '2022-03-22T14:48:20+09:00'
    start: '2022-03-22T14:27:39+09:00'
