version: v0.2.0
description: Training data for Pilot Challenge
url: https://zenodo.org/record/6697990
release_date: '2022-06-23'
users:
  U0102:
    sessions:
    - S0100
    - S0200
    - S0300
    - S0400
    - S0500
  U0103:
    sessions:
    - S0100
    - S0200
    - S0300
    - S0400
    - S0500
  U0105:
    sessions:
    - S0100
    - S0200
    - S0300
    - S0400
    - S0500
  U0106:
    sessions:
    - S0100
    - S0200
    - S0300
    - S0400
    - S0500
streams:
  atr:
    repository: zenodo
    subdirs: ${.devices}
    devices:
    - atr01
    - atr02
    - atr03
    - atr04
  kinect:
    2d-kpt:
      repository: zenodo
      subdirs:
      - name: ${.model}
        category: 2d-kpt
        model: mmpose-hrnet-w48-posetrack18-384x288-posewarper-stage2
        subdir: single
        fname: kinect-2d-kpt
  annotation:
    repository: zenodo
    subdirs:
    - openpack-operations
